# Generated by Django 2.0.7 on 2019-11-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.IntegerField(primary_key=True, serialize=False)),
                ('driver_id', models.IntegerField()),
                ('passenger_id', models.IntegerField()),
                ('date', models.DateField()),
                ('pick_up', models.TextField()),
                ('drop_off', models.TextField()),
            ],
        ),
    ]
