# Generated by Django 2.0.7 on 2019-11-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
