# Generated by Django 2.0.7 on 2019-11-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20191124_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='passenger_id',
        ),
        migrations.AddField(
            model_name='driver',
            name='username',
            field=models.TextField(default='noname'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='username',
            field=models.TextField(default='noname'),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_username',
            field=models.TextField(default='noname'),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger_username',
            field=models.TextField(default='noname'),
        ),
    ]
