# Generated by Django 2.0.7 on 2019-11-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20191124_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='time_arr',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='time_dep',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='time_arr',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='time_dep',
            field=models.TimeField(),
        ),
    ]
