# Generated by Django 2.0.7 on 2019-11-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_auto_20191124_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
