# Generated by Django 2.0.7 on 2019-11-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_auto_20191124_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='time_arr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='time_dep',
            field=models.FloatField(),
        ),
    ]
