# Generated by Django 2.0.7 on 2019-11-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_auto_20191125_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='stops_arr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='time_arr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='time_dep',
            field=models.FloatField(),
        ),
    ]
