# Generated by Django 2.0.7 on 2019-11-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_auto_20191125_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver_ride_id',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger_ride_id',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='drivers.Passenger'),
            preserve_default=False,
        ),
    ]
